// Copyright 2019 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    final allProducts = [
      Product(
        category: categoryWine,
        id: 0,
        isFeatured: true,
        
        name: "Cabernet Shiraz",
        price: 120,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryWine,
        id: 1,
        isFeatured: true,
        name: "Sette",
        price: 58,
        assetAspectRatio: 329 / 247,
      ),
      Product(
        category: categoryWine,
        id: 2,
        isFeatured: false,
        name: "Big Banyan",
        price: 35,
        assetAspectRatio: 329 / 228,
      ),
      Product(
        category: categoryWine,
        id: 3,
        isFeatured: true,
        name: "Four Seasons",
        price: 98,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryWine,
        id: 4,
        isFeatured: false,
        name: "La Reserve",
        price: 34,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryWine,
        id: 5,
        isFeatured: false,
        name: 'Reserve Tempranillo',
        price: 12,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryWine,
        id: 6,
        isFeatured: false,
        name: 'York Arros',
        price: 16,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryWine,
        id: 7,
        isFeatured: true,
        name: 'KRSMA Sangiovese',
        price: 40,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryWine,
        id: 8,
        isFeatured: true,
        name: 'Myra Cabernet',
        price: 198,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 9,
        isFeatured: true,
        name: "Kingfisher",
        price: 58,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 10,
        isFeatured: false,
        name: "Carlsberg",
        price: 18,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 11,
        isFeatured: false,
        name: "Budweiser",
        price: 28,
        assetAspectRatio: 329 / 247,
      ),
      Product(
        category: categoryBeer,
        id: 12,
        isFeatured: false,
        name: "Tuborg",
        price: 34,
        assetAspectRatio: 329 / 213,
      ),
      Product(
        category: categoryBeer,
        id: 13,
        isFeatured: true,
        name: 'Heineken',
        price: 18,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 14,
        isFeatured: true,
        name:'Foster',
        price: 27,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 15,
        isFeatured: true,
        name: 'Haywards',
        price: 16,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 16,
        isFeatured: true,
        name: 'Godfather',
        price: 16,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryBeer,
        id: 17,
        isFeatured: false,
        name: 'Hoegaarden',
        price: 175,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryVodka,
        id: 18,
        isFeatured: true,
        name: 'Smirnoff',
        price: 129,
        assetAspectRatio: 329 / 246,
      ),
      Product(
        category: categoryVodka,
        id: 19,
        isFeatured: false,
        name: 'Absolut',
        price: 48,
        assetAspectRatio: 329 / 219,
      ),
      Product(
        category: categoryVodka,
        id: 20,
        isFeatured: false,
        name: 'Grey Goose:',
        price: 45,
        assetAspectRatio: 329 / 221,
      ),
      Product(
        category: categoryVodka,
        id: 21,
        isFeatured: false,
        name: 'Belvedere',
        price: 38,
        assetAspectRatio: 220 / 329,
      ),
      Product(
        category: categoryVodka,
        id: 22,
        isFeatured: false,
        name: 'Ciroc',
        price: 70,
        assetAspectRatio: 219 / 329,
      ),
      Product(
        category: categoryVodka,
        id: 23,
        isFeatured: false,
        name: 'Beluga',
        price: 70,
        assetAspectRatio: 329 / 221,
      ),
      Product(
        category: categoryVodka,
        id: 24,
        isFeatured: true,
        name: 'Finlandia',
        price: 60,
        assetAspectRatio: 220 / 329,
      ),
      Product(
        category: categoryVodka,
        id: 25,
        isFeatured: false,
        name: 'Siberian',
        price: 178,
        assetAspectRatio: 329 / 219,
      ),
      Product(
        category: categoryVodka,
        id: 26,
        isFeatured: false,
        name: 'Stolichnaya',
        price: 74,
        assetAspectRatio: 220 / 329,
      ),
      Product(
        category: categoryVodka,
        id: 27,
        isFeatured: true,
        name: 'Toto',
        price: 38,
        assetAspectRatio: 219 / 329,
      ),
      Product(
        category: categoryVodka,
        id: 28,
        isFeatured: true,
        name: 'Zouk',
        price: 48,
        assetAspectRatio: 329 / 219,
      ),
      Product(
        category: categoryVodka,
        id: 29,
        isFeatured: true,
        name: 'Comte de',
        price: 98,
        assetAspectRatio: 219 / 329,
      ),
      Product(
        category: categoryVodka,
        id: 30,
        isFeatured: true,
        name: 'Pravda',
        price: 68,
        assetAspectRatio: 220 / 329,
      ),

      Product(
        category: categoryRum,
        id: 31,
        isFeatured: false,
        name: 'Old Monk',
        price: 38,
        assetAspectRatio: 329 / 223,
      ),
      Product(
        category: categoryRum,
        id: 31,
        isFeatured: false,
        name: 'Clement',
        price: 38,
        assetAspectRatio: 329 / 223,
      ),
      Product(
        category: categoryRum,
        id: 31,
        isFeatured: false,
        name: 'El Dorado',
        price: 38,
        assetAspectRatio: 329 / 223,
      ),
      Product(
        category: categoryWhisky,
        id: 31,
        isFeatured: false,
        name: 'Glenkinchie 12',
        price: 38,
        assetAspectRatio: 329 / 223,
      ),
      Product(
        category: categoryWhisky,
        id: 32,
        isFeatured: false,
        name:'Black Dog',
        price: 58,
        assetAspectRatio: 221 / 329,
      ),
      Product(
        category: categoryWhisky,
        id: 33,
        isFeatured: true,
        name: 'Rampur',
        price: 42,
        assetAspectRatio: 329 / 219,
      ),
      Product(
        category: categoryWhisky,
        id: 34,
        isFeatured: false,
        name: 'Amrut',
        price: 27,
        assetAspectRatio: 220 / 329,
      ),
      Product(
        category: categoryWhisky,
        id: 35,
        isFeatured: false,
        name: 'Indri',
        price: 24,
        assetAspectRatio: 222 / 329,
      ),
      Product(
        category: categoryWhisky,
        id: 36,
        isFeatured: false,
        name: 'Paul John',
        price: 58,
        assetAspectRatio: 219 / 329,
      ),
      Product(
        category: categoryWhisky,
        id: 37,
        isFeatured: true,
        name: 'Kamet',
        price: 58,
        assetAspectRatio: 219 / 329,
      ),
    ];
    if (category == categoryAll) {
      return allProducts;
    } else {
      return allProducts.where((p) => p.category == category).toList();
    }
  }
}
